name: Build and Publish

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: 6.0.100
  NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build
        run: msbuild /p:Configuration=Release

      - name: Pack
        run: msbuild /t:Pack /p:Configuration=Release

      - name: Publish to GitHub Packages
        run: dotnet nuget push "bin/Release/*.nupkg" --source "${{ env.NUGET_ENDPOINT }}" --api-key "${{ env.NUGET_API_KEY }}"
        env:
          NUGET_ENDPOINT: https://nuget.pkg.github.com/LuminationDev/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_TOKEN }}
